# debian
FROM debian

# sets workdir to syssec-build
WORKDIR syssec-build/


# install the required packages
RUN apt-get update && apt-get --no-install-recommends install -y \
    texlive-base \
    texlive-latex-recommended \
    texlive-latex-extra \
    texlive-science \
    texlive-bibtex-extra \
    biber \
    latexmk \
    wget \
    xzdec

# initializes tlmgr
RUN tlmgr init-usertree

# install the packages
RUN tlmgr install \ 
    ccicons \
    tracklang
